### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [dakyion/theophysics-personal#1]
I recently came across your project theophysics-personal and I noticed that the repository github.com/dakyion/theophysics-personal currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by dakyion** [comment]
@cbjuan
Thank you for notifying me about the issue of licensing!
I had a problem selecting the right license.
I would appreciate if you point me to the right license that verify these two points:
- Anyone can use and/or modify the code.
- Modified versions of my project that are meant to be externally redistributed must be open source and mention the original project (i.e. this one).

**Comment by cbjuan** [comment]
Hi. As referred on GitHub's documentation, you could use the website https://choosealicense.com/ to find which one fits best for you

**Comment by cbjuan** [comment]
Thanks!

**Comment by dakyion** [comment]
@cbjuan  You are welcome!
